update scripts

diff --git a/k8s/cronjob/pipeline-script-configmap.yaml b/k8s/cronjob/pipeline-script-configmap.yaml
--- a/k8s/cronjob/pipeline-script-configmap.yaml
+++ b/k8s/cronjob/pipeline-script-configmap.yaml
@@ -5,7 +5,11 @@ metadata:
 data:
   run-pipeline.sh: |
     #!/bin/bash
-    set -e
+    set -eo pipefail
+
+    log() {
+        echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
+    }
 
     job_files=(
       "01-collect-job-listings.yaml"
@@ -18,7 +22,7 @@ data:
     for job_file in "${job_files[@]}"; do
       job=$(echo $job_file | sed 's/^[0-9]*-//; s/\.yaml$//')
       
-      echo "Starting job: $job"
+      log "Starting job: $job"
       timestamp=$(date +%s)
       job_name="$job-$timestamp"
       
@@ -31,31 +35,29 @@ data:
         if [ "$status" == "True" ]; then
           end_time=$(date +%s)
           duration=$((end_time - start_time))
-          echo "Job $job completed successfully in $duration seconds"
+          log "Job $job completed successfully in $duration seconds"
           break
         elif [ "$status" == "False" ]; then
-          echo "Job $job failed"
+          log "Job $job failed"
           kubectl logs job/$job_name
           exit 1
         else
           current_time=$(date +%s)
           elapsed=$((current_time - start_time))
-          echo "Job $job still running after $elapsed seconds..."
+          log "Job $job still running after $elapsed seconds..."
           
-          # Check for pod status
           pod_status=$(kubectl get pods --selector=job-name=$job_name -o jsonpath='{.items[*].status.phase}')
-          echo "Pod status: $pod_status"
+          log "Pod status: $pod_status"
           
-          # If the pod is running, tail the logs
           if [ "$pod_status" == "Running" ]; then
-            echo "Recent logs:"
+            log "Recent logs:"
             kubectl logs job/$job_name --tail=5
           fi
         fi
-        sleep 300  # Check every 5 minutes
+        sleep 300
       done
 
       kubectl delete job $job_name
     done
 
-    echo "Pipeline completed successfully"
+    log "Pipeline completed successfully"
